on:
    pull_request:
      paths-ignore:
        - 'docs/**'
        - 'README.md'
        - 'CHANGELOG.md'
        - '.gitignore'
        - '.gitattributes'
        - 'infection.json.dist'
        - 'phpunit.xml.dist'

    push:
      paths-ignore:
        - 'docs/**'
        - 'README.md'
        - 'CHANGELOG.md'
        - '.gitignore'
        - '.gitattributes'
        - 'infection.json.dist'
        - 'phpunit.xml.dist'

name: ecs

jobs:
  easy-coding-standard:
    uses: yiisoft/actions/.github/workflows/ecs.yml@master
    with:
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.1']
